server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/shamim
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: shamim@@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
