server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
