server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.17.0.3:3306/microservice
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: shamim@@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect